<a href="https://colab.research.google.com/github/deltorobarba/machinelearning/blob/master/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Algebraic Structures (Abstract Algebra)**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## **Algebraic Operations**

#### **Introduction**

* Algebra ist das Lösen von Gleichungen.

* **Eine [Algebraische Struktur](https://de.m.wikipedia.org/wiki/Algebraische_Struktur) & [Outline_of_algebraic_structures](https://en.m.wikipedia.org/wiki/Outline_of_algebraic_structures) ist eine Menge versehen mit Verknüpfungen auf dieser Menge**. Eine Vielzahl der in der abstrakten Algebra untersuchten Strukturen wie Gruppen, Ringe oder Körper sind spezielle algebraische Strukturen.

* Algebraische Strukturen sind eine Form von [mathematischen Strukturen](https://de.m.wikipedia.org/wiki/Mathematische_Struktur) (neben topologischen Strukturen, geometrischen Strukturen und Zahlbereichen). Abstract algebra is the study of algebraic structures.

* **Such a structure consists of a set together with one or more binary operations, which are required to satisfy certain axioms.**

* The structures listed below are only a sample of the many algebraic structures of importance in mathematics. Many fields of mathematics involve their own special algebraic structures, and new algebraic structures are defined all the time. To give you a sense of scale, the online encyclopedia Wikipedia currently has articles on over a hundred different algebraic structures, and this represents only a small fraction of those that have been investigated in the mathematical literature.

* **[Verknüpfungen](https://de.m.wikipedia.org/wiki/Verknüpfung_(Mathematik))**: Neben den arithmetischen Grundrechenarten (Addition, Subtraktion usw.) werden damit etwa auch geometrische Operationen (wie Spiegelung, Drehung u. a.) sowie weitere Rechenoperationen bzw. gelegentlich auch logische Operatoren erfasst. 
  * **Verknüpfungen dienen in der Algebra dazu, algebraische Strukturen zu definieren**. Die Verknüpfungen müssen dabei bestimmte Bedingungen (Axiome) erfüllen. Bei partiellen Algebren sind auch partielle Verknüpfungen zugelassen.
  * Zum Beispiel ist eine Halbgruppe eine Menge mit einer inneren zweistelligen Verknüpfung, die das Assoziativgesetz erfüllt. Die Forderung, dass das Ergebnis der Verknüpfung wieder Element der gegebenen Menge sein soll (Abgeschlossenheit), ist bereits in der Definition der inneren Verknüpfung enthalten.

#### **Elementare Algebra**

https://de.wikipedia.org/wiki/Elementare_Algebra

https://de.wikipedia.org/wiki/Binomische_Formeln

#### **Regeln**

**[Abgeschlossenheit](https://de.m.wikipedia.org/wiki/Abgeschlossenheit_(algebraische_Struktur))**

* Closure laws: a + b and ab are unique elements in the field.

* Manchmal findet man noch die Forderung der „Abgeschlossenheit“, dass 
x
∗
y
wieder in 
G liegen soll, aber aus der Sicht eines Algebraikers beinhaltet der Begriff der „zweistelligen Verknüpfung“ diese Eigenschaft bereits.

Manchmal findet man noch die Forderung der „Abgeschlossenheit“, dass x ∗ y wieder in G liegen soll, aber aus der Sicht eines Algebraikers beinhaltet der Begriff der „zweistelligen Verknüpfung“ diese Eigenschaft bereits.

*Nur Abgeschlossenheit gilt für Magma (Groupoid)*

**[Assoziativität](https://de.m.wikipedia.org/wiki/Assoziativgesetz)**

* **Addition**. When three or more numbers are added, the sum is the same regardless of the way in which the numbers are grouped. (a + b) + c = a + (b + c)

* **Multiplication**. When three or more numbers are multiplied, the product is the same regardless of the way in which the numbers are grouped. (a * b) * c = a * (b * c)

See also [**Associative_property**](https://en.wikipedia.org/wiki/Associative_property) and [**Non associative algebra** (or distributive algebra)](https://en.wikipedia.org/wiki/Non-associative_algebra). For example: "Because matrices represent linear functions, and matrix multiplication represents function composition, one can immediately conclude that matrix multiplication is associative."

* A non-associative algebra (or distributive algebra) is an algebra over a field where the binary multiplication operation is not assumed to be associative. That is, an algebraic structure A is a non-associative algebra over a field K if it is a vector space over K and is equipped with a K-bilinear binary multiplication operation A × A → A which may or may not be associative. 

* Examples include Lie algebras, Jordan algebras, the octonions, and three-dimensional Euclidean space equipped with the cross product operation. 

*Abgeschlossenheit und Assoziativität gilt für Halbgruppen*

**[Identity Property](https://en.m.wikipedia.org/wiki/Identity_element) (Neutrales Element)**

* **Additive identity**. The sum of any number and zero is that number. 12 + 0 = 12

* **Multiplicatice identity**, The product of any number and one is that number. 18 x 1 = 18

*Zusätzlich Identity gilt für Monoid (Teiltyp Gruppe)*

**[Inverse Elemente](https://de.m.wikipedia.org/wiki/Inverses_Element)**

* **In Algebra you don't talk about substraction and division. It is additive inverse & multiplicative inverse!** This is important for fields (Korper)!

* For each element a $\in \mathrm{G}$, there exists an element $\mathrm{a}^{-1} \in \mathrm{G}$ such that $\mathrm{a} \cdot \mathrm{a}^{-1}=\mathrm{a}^{-1} \cdot \mathrm{a}=\mathrm{e}$. (The element $\mathrm{a}^{-1}$ is called the inverse of a.)

* Wenn man ein beliebiges Element der Menge und sein Inverses mit der Rechenoperation verknüpft, erhält man immer das sogenannte neutrale Element $\mathrm{e}$ als Ergebnis.

* **Addition**: a+(-a) = a-a = 0 zB: 7 + (-7) = 0

* **Multiplication**: Two elements of a set, A and A inverse, multiplied together to produce the identity element. Zahl a multipliziert mit seinem Kehrwert (1/a oder a<sup>-1</sup>) = 1

*Zusätzlich Inverse gilt für Gruppe*

**[Kommutativität](https://de.m.wikipedia.org/wiki/Kommutativgesetz)**

* **Addition**. When two numbers are added, the sum is the same regardless of the order in which the numbers are added. a + b = b + a

* **Multiplication**. When two numbers are multiplied together, the product is the same regardless of the order in which the numbers are multiplied. a * b = b * a

*Zusätzlich Kommutativität gilt für Abelian Group*

For more details on sub-types of groups, see Group-like structures: https://en.m.wikipedia.org/wiki/Category_(mathematics)

**[Distributivgesetz](https://de.m.wikipedia.org/wiki/Distributivgesetz)**

* The sum of two numbers times a third number is equal to the sum of each addend times the third number (Gilt für körper (fields), aber nicht gruppen oder ringe!). a * b + a * c = a * (b + c)

*Gilt zusätzlich Distributivgesetz gilt für Ring (da man hier zwei Operationen benötigt)*

#### **Summary**

$+$ $\quad$ $-$ $\quad$ is a Group

$+$ $\quad$ $-$ $\quad$ $\cdot$ $\quad$ is a Ring

$+$ $\quad$ $-$ $\quad$ $\cdot$ $\quad$ $÷$ $\quad$ is a Field



**The elements of a field (Körper) obey the following laws:**

1. **Closure laws**: a + b and ab are unique elements in the field.

2. **Commutative laws**: a + b = b + a and ab = ba.

3. **Associative laws**: a + (b + c) = (a + b) + c and a(bc) = (ab)c.

4. **Identity laws**: there exist elements 0 and 1 such that a + 0 = a and a × 1 = a.

5. **Inverse laws**: for every a there exists an element - a such that a + (-a) = 0, and for every a ≠ 0 there exists an element a-1 such that a × a-1 = 1.

6. **Distributive law**: a(b + c) = ab + ac.


Read more: Field - Set, Laws, Elements, and Operations - JRank Articles https://science.jrank.org/pages/2709/Field.html#ixzz6UdPamPNB

* **Summary**: Aus einer Menge der Zahlen (N, Z, Q, R, C, H) eine algebraische Struktur basteln. Man kann mit der Gruppe anfangen (als einfachste algebraische Struktur), um erstmal einfach zu verknüpfen. Dann schickt man noch eine Verknüpfung rein und bastelt sich so einen Ring. Kommt dann zum Körper und kann spätestens bei den Körpern über komplexen Zahlen sämtliche Gleichungen lösen.

* **Gruppe** zB schickt man die Menge natürliche Zahlen N in eine zweistellige Verknüpfung. Wobei abgestuft werden kann wie viele Axiome gelten, von Magma, über Halbgruppe (nur Assoziativität), Monoid (inkl. neutrales Element), Gruppe (inkl Inverse) und Abelsche Gruppe (inkl Kommutativität).

* **Ringe** erlauben **zwei** zweistellige Verknüpfungen, üblicherweise der **ganzen Zahlen Z**, was aber kein Divisionsring ist / keine multiplikative Inverse für alle Elemente (gibt Probleme bei der Lösung mancher Gleichungen): Addition: (R, +) ist eine abelsche Gruppe, aber die Multiplikation: (R, ∙) ist eine Halbgruppe. **Kommutativität in der Multiplikation gilt dann erst bei Körpern!**

* Divisionsring = Schiefkörper (hat alle Körpereigenschaften, aber die Multiplikation ist nicht notwendigerweise kommutativ). Anwendung bei Quaternions H.

* **Körper** über rationale Zahlen Q, über reelle Zahlen R und über komplexe Zahlen C. Damit kann man praktisch alle Gleichungen lösen. Bei Körpern gilt die Kommutativität in der Multiplikation.

* Für Operationen im mehrdimensionalen Raum erweitert man noch auf **Module** (für Ringe, zB ganze Zahlen Z<sup>n</sup>) und **Vektorräume** (für Körper, zB reelle Zahlen R<sup>n</sup>). Deshalb sagt man auch zB Vektorraum über einen Körper der reellen Zahlen. **Ein Modul ist ein n-dimensionaler Ring, und ein Vektorraum ist ein n-dimensionaler Körper.**

![alternativer Text](https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Übersicht_Körper.svg/993px-Übersicht_Körper.svg.png)


https://en.m.wikipedia.org/wiki/Vector_space

https://en.m.wikipedia.org/wiki/Outline_of_algebraic_structures

<img src="https://raw.githubusercontent.com/deltorobarba/repo/master/algebragroups.jpg" alt="algreba">

https://youtu.be/Cq2m-MgczWU

## **Gruppen**

#### **Introduction**

Eulerformel und Gruppentheorie: https://youtu.be/mvmuCPvRoWQ

**Group Theory is all about Symmetrie, here better called Isomorphism!**

**Applications of Group Theory**

* Solutions to polynomial equations, like find 2 roots of a quadratic equation. there is also q cubic formula and a quartic for degree 4 polynomial. Find formula to solve degree 5 polynomial - group theory showed it doesnt exist. Has to do with permutation group S5.

* Connection to Physics - Noether's theorem: Conservation law - symmetry. Momentum - translation in space. Energy - translation in time.

https://www.youtube.com/watch?v=mH0oCDa74tE

https://en.wikipedia.org/wiki/Monstrous_moonshine

https://de.m.wikipedia.org/wiki/Geometrische_Gruppentheorie

#### **Properties**

A group is a set $G$ with an operation $*$ such that

* **Closure**: If $x$ and $y$ are in $G$ then $x * y$ is in $\mathrm{G}$
  * until here it is a **Magma (Groupoid)**

* **Associativity**: For all $x, y, z$ in $G$ $\text { we have }(x * y) * z=x *(y * z)$
  * until here it is a **Halbgruppe**

* **Identity Element**: There is an element $e$ in $G$ such that $e * x=x * e=x$ for all $x$ in $G$
  * until here it is a **Monoid**

* **Inverse Elements**: For each element $x$ in $G,$ there is an element $x^{-1}$ such that $x * x^{-1}=x^{-1} * x=e$
  * until here it is a **Group**

* **Kommutative**: Für alle $a, b \in G$ gilt: $a * b=b * a$
  * until here it is an **Abel'sche Gruppe**

![xxx](https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Algebraische_Strukturen.svg/498px-Algebraische_Strukturen.svg.png)

https://de.m.wikipedia.org/wiki/Gruppentheorie

https://de.m.wikipedia.org/wiki/Gruppe_(Mathematik)

* Die fundamentalen algebraischen Strukturen besitzen eine oder zwei [zweistellige innere Verknüpfungen](https://de.m.wikipedia.org/wiki/Zweistellige_Verknüpfung). 

* Gruppen sind algebraische Strukturen mit einer inneren Verknüpfung

* **A group is an algebraic structure with a single operation**. 

* Groups are closely associated with the idea of symmetry, and most groups that arise in mathematics are groups of symmetry transformations, with the operation being composition of functions.

* **Groups are a particularly simple algebraic structure**, having only one operation and three axioms. Most algebraic structures have more than one operation, and are required to satisfy a long list of axioms.

A group is a set G together with a binary operation ∗ on G, satisfying the following axioms:

1. **Abgeschlossenheit** (für **Magma**, ohne assoziativität, inverse, identity oder kommutativ)

2. **Assoziativität**: The operation ∗ is associative. That is,
a ∗ (b ∗ c) = (a ∗ b) ∗ c
for all a,b,c ∈ G. (für **Halbgruppen**, ohne identity, inverse oder kommutativ)

3. **Identity Element**: There exists an element e ∈ G with the property that
a∗e=e∗a=a
for all a ∈ G. (This element e is called the identity element of G.) für **Monoid** (ein Monoid ist eine Halbgruppe, die ein neutrales Element besitzt)

4. **Inverse**: For each element a ∈ G, there exists an element a<sup>-1</sup> ∈ G such that a∗􏰁a<sup>-1</sup>􏰂 = 􏰁a<sup>-1</sup>􏰂∗a = e.
(The element a<sup>-1</sup> is called the inverse of a.) für **Gruppe** (Eine Gruppe ist also ein Monoid, in dem jedes Element ein Inverses hat.)

5. **Kommutativität**: für **Abelsche Gruppen**

**Von der Magma zur Abel'schen Gruppe**: Die Grundmenge ist unter einer inneren Verknüpfung per Definition abgeschlossen. Ansonsten muss ein Magma keine speziellen Eigenschaften haben. Durch Hinzunahme weiterer Bedingungen werden speziellere Strukturen definiert, die alle wiederum Magmen sind. Typische Beispiele sind:

* Halbgruppe: ein Magma, dessen Verknüpfung assoziativ ist

* Monoid: eine Halbgruppe mit einem neutralen Element

* Quasigruppe: ein Magma, in dem alle Gleichungen der Form 
a
x
=
b
ax=b oder 
x
a
=
b
xa=b eindeutig nach 
x
x auflösbar sind

* Loop: eine Quasigruppe mit einem neutralen Element

* Gruppe: ein Monoid, in dem jedes Element ein Inverses hat

* Abelsche Gruppe: eine Gruppe, deren Verknüpfung kommutativ ist

* Mediales Magma: ein Magma, in dem für alle Elemente die Gleichung 
(
a
⋆
b
)
⋆
(
c
⋆
d
)
=
(
a
⋆
c
)
⋆
(
b
⋆
d
)
(a\star b)\star (c\star d)=(a\star c)\star (b\star d) gilt

**Gruppenoperation**

https://de.m.wikipedia.org/wiki/Gruppenoperation

**Konjugation (Gruppentheorie)**

https://de.m.wikipedia.org/wiki/Konjugation_(Gruppentheorie)

#### **Algebraic Group Structures**

##### **Gruppoid (Magma)**

* ein Magma (neutrum, Mehrzahl Magmen) ist eine algebraische Struktur, bestehend aus einer Menge zusammen mit einer zweistelligen inneren Verknüpfung. 

* Es wird auch Gruppoid,manchmal Binar oder Operativ genannt.

* Ist die Verknüpfung kommutativ, so heißt das Magma kommutativ oder abelsch; ist sie assoziativ, so heißt das Magma assoziativ oder Halbgruppe.

Die folgenden **Beispiele** sind Magmen, die keine Halbgruppen sind:

* $(\mathbb{Z},-):$ die ganzen Zahlen mit der Subtraktion

* (R $\backslash\{0\}, /)$ : die reellen Zahlen ungleich 0 mit der Division

* Die natürlichen Zahlen mit der Exponentiation, also mit der Verknüpfung $a * b=a^{b}$

* Die reellen Zahlen mit der Bildung des arithmetischen Mittels als Verknüpfung

https://de.m.wikipedia.org/wiki/Magma_(Mathematik)

Gruppoid (Kategorientheorie)

**Achtung:** Siehe Gruppoid in der Kategorientheorie: https://de.m.wikipedia.org/wiki/Gruppoid_(Kategorientheorie)

* Die drei Verträglichkeitsbedingungen gleichen den Gruppenaxiomen. Das ist kein Zufall. 

* **Ein Gruppoid mit genau einem Objekt ist nichts anderes als eine Gruppe**. In diesem Sinn stellt der Begriff Gruppoid also eine Verallgemeinerung des Begriffes Gruppe dar.

* Die Kategorie aller Gruppoide mit Funktoren als Morphismen ist eine Subkategorie von Cat, der Kategorie aller kleinen Kategorien

Infinity Groupoid


* The notion of ∞-groupoid is the generalization of that of group and groupoids to higher category theory:

https://ncatlab.org/nlab/show/infinity-groupoid

https://en.m.wikipedia.org/wiki/∞-groupoid

##### **Halbgruppe**

* **Abgeschlossenheit** (https://de.m.wikipedia.org/wiki/Abgeschlossenheit_(algebraische_Struktur))

* **Assoziativität**: The operation ∗ is associative. That is, a ∗ (b ∗ c) = (a ∗ b) ∗ c for all a,b,c ∈ G.

Es wird **nicht** erfüllt: Neutral (identity element), inverse, kommunitativ  (Abel'sche Gruppe)

Beispiele: 

* Die Menge $\mathbb  N$ $_0$ = {0, 1, 2 ..} der natürlichen Zahlen bildet mit der gewöhnlichen Addition eine kommutative und kürzbare Halbgruppe ($\mathbb  N$ $_0$,+), die keine Gruppe ist. Da hier die negativen Zahlen fehlen, also die „Hälfte“ der abelschen Gruppe ($\mathbb Z,+$) der ganzen Zahlen, lag der Name Halbgruppe für diese mathematische Struktur nahe. 

* Tatsächlich wurde in der Vergangenheit der Begriff „Halbgruppe“ für ein nach den oben gegebenen Definitionen kommutatives, kürzbares Monoid verwendet, später setzte sich dann die obige Definition allgemein durch.

https://de.m.wikipedia.org/wiki/Halbgruppe

##### **Monoid**

* **Closure**: If $x$ and $y$ are in $G$ then $x * y$ is in $\mathrm{G}$

* **Associativity**: For all $x, y, z$ in $G$ $\text { we have }(x * y) * z=x *(y * z)$

* **Identity Element**: There is an element $e$ in $G$ such that $e * x=x * e=x$ for all $x$ in $G$

Es wird **nicht** erfüllt: inverse Element (= Gruppe), kommunitativ (= Abel'sche Gruppe)

* ein Monoid ist eine algebraische Struktur bestehend aus einer Menge mit einer klammerfrei notierbaren (assoziativen) Verknüpfung und einem neutralen Element. 

* **Ein Beispiel sind die natürlichen Zahlen mit der Addition und der Zahl 0 als neutralem Element.** 

* Ein Monoid, in dem jedes Element invertierbar ist, heißt Gruppe.

* Eigenschaften bezüglich der angegebenen Verknüpfung: Assoziativität der Verknüpfung und e ist ein neutrales Element.

* **Ein Monoid ist also eine Halbgruppe mit neutralem Element.** Jede Gruppe ist ein Monoid, aber ein Monoid hat im Gegensatz zur Gruppe nicht notwendigerweise inverse Elemente.

* in Kategorietheorie ein Monoid ist eine Kategorie mit nur einem Objekt (und Pfeile mit Richtung zu sich selbst als Elemente / das sind neutrale Elemente)


https://de.m.wikipedia.org/wiki/Monoid

##### **Gruppe**

A group is a set $G$ with an operation $*$ such that

* **Closure**: If $x$ and $y$ are in $G$ then $x * y$ is in $\mathrm{G}$

* **Associativity**: For all $x, y, z$ in $G$ $\text { we have }(x * y) * z=x *(y * z)$

* **Identity Element**: There is an element $e$ in $G$ such that $e * x=x * e=x$ for all $x$ in $G$

* **Inverse Elements**: For each element $x$ in $G,$ there is an element $x^{-1}$ such that $x * x^{-1}=x^{-1} * x=e$

* Demnach ist eine Gruppe eine Menge zusammen mit **einer zweistelligen inneren Verknüpfung** (durch die jedem geordneten Paar von Elementen eindeutig ein Element dieser Menge als Resultat zugeordnet wird), wenn diese **Verknüpfung assoziativ** ist und es ein **neutrales Element** gibt sowie zu jedem Element ein **Inverses**. 

**Ringe, Körper, Moduln und Vektorräume sind Gruppen mit zusätzlichen Strukturen und Eigenschaften**

Beispiele

* So bildet zum Beispiel auch die Menge der ganzen Zahlen zusammen mit der Addition eine Gruppe.

* Physik und Chemie treten Gruppen überall dort auf, wo Symmetrien eine Rolle spielen (z. B. Invarianz physikalischer Gesetze, Symmetrie von Molekülen und Kristallen)

##### **Abelian Group**

https://www.math.uni-bielefeld.de/~sek/top/leit/alg2.htm

* Eine abelsche Gruppe ist eine Gruppe, für die zusätzlich das Kommutativgesetz gilt.

Sei $G$ eine Menge. Jedem Paar $(a, b) \in G \times G$ sei genau ein Element $a * b \in G$ zugeordnet. Das Paar $(G, *)$ heißt abelsche Gruppe, wenn die Verknüpfung $*: G \times G \rightarrow G,(a, b) \mapsto a * b$ die folgenden Gesetze erfüllt:

1. Assoziativgesetz: Für alle $a, b, c \in G$ gilt: $a *(b * c)=(a * b) * c$
2. Kommutativgesetz: Für alle $a, b \in G$ gilt: $a * b=b * a$
3. Neutrales Element: Es gibt ein Element $e \in G,$ so dass für alle $a \in G$ gilt: $a * e=a$
4. Inverses Element: Zu jedem $a \in G$ gibt es ein $a^{-1} \in G$ mit $a * a^{-1}=e$.

Eine Gruppe $(G, *)$ heißt nichtabelsch, wenn in ihr mindestens ein Paar $(a, b)$ existiert mit $a * b \neq b * a$

* $(\mathbb {Z} ,+)$ ist die wichtigste abelsche Gruppe. Dabei ist Z die Menge der ganzen Zahlen und + die gewöhnliche Addition.

* $(\mathbb {Q} ^{*},\cdot )$ ist eine abelsche Gruppe. Dabei ist $\mathbb {Q} ^{*}$ die Menge der rationalen Zahlen ohne die 
0 und ⋅ ist die gewöhnliche Multiplikation. Die Null muss hierbei ausgeschlossen werden, da sie kein inverses Element besitzt: „1/0“ ist nicht definiert.

* Die Menge der Verschiebungen in der euklidischen Ebene bilden eine abelsche Gruppe. Die Verknüpfung ist die Hintereinanderausführung der Verschiebungen.

* Die Menge der Drehungen in einer Ebene um einen Punkt bilden eine abelsche Gruppe. Die Verknüpfung ist die Hintereinanderausführung der Drehungen.

* Die Menge der Drehstreckungen in einer Ebene bilden eine abelsche Gruppe.

* Die Menge der endlichen Dezimalzahlen sind bezüglich der Multiplikation keine abelsche Gruppe. Zum Beispiel hat die Zahl 3 kein Inverses bezüglich der Multiplikation. $\displaystyle {\frac {1}{3}}$ lässt sich nicht als endlicher Dezimalbruch schreiben. Bezüglich der normalen Addition bilden die endlichen Dezimalbrüche eine abelsche Gruppe.
Die Menge der Verschiebungen in der euklidischen Ebene bilden eine abelsche Gruppe. Die Verknüpfung ist die Hintereinanderausführung der Verschiebungen.

* usw.: https://de.m.wikipedia.org/wiki/Abelsche_Gruppe

**Freie Abelsche Gruppe**

* In der Mathematik ist eine freie abelsche Gruppe eine abelsche Gruppe, die als $\mathbb {Z}$-Modul eine Basis hat.

* Im Gegensatz zu Vektorräumen hat nicht jede abelsche Gruppe eine Basis, deshalb gibt es den spezielleren Begriff der freien abelschen Gruppe.

* Jede abelsche Gruppe ist auf natürliche Weise ein $\mathbb {Z}$ -Modul. Freie abelsche Gruppen sind daher nichts anderes als freie Moduln über $\mathbb {Z}$.

https://de.m.wikipedia.org/wiki/Freie_abelsche_Gruppe

https://de.m.wikipedia.org/wiki/Freier_Modul

**Bedeutung (freier) abelscher Gruppen**

* Kann man von einer irgendwo in natürlicher Weise auftretenden Gruppe G zeigen, dass G eine freie abelsche Gruppe ist, so freut man sich:  denn es zeigt, **dass G eine sehr übersichtliche Struktur besitzt, dass man in G recht unproblematisch rechnen kann.** 

* Beispiel:  Ist V ein k-Vektorraum, wobei k ein Körper der Charakteristik Null ist, so ist jede Untergruppe von V, die von endlich vielen Vektoren erzeugt wird, eine freie abelsche Gruppe. (Wenn wir von Untergruppen von V reden, so betrachten wir nur die additive Struktur von V: Jeder Vektorraum ist ja bezüglich der Addition eine abelsche Gruppe.) 

* Weiß man, dass G eine freie abelsche Gruppe ist, **so wird man eine Basis wählen und alle Elemente als Linearkombinationen von Elementen dieser Basis ausdrücken**. Allerdings sollte man betonen, dass es meist keine ausgezeichnete Basis geben wird. Man sucht also eine geeignete Basis, in der die Elemente, an denen man interessiert sind, eine besonders einfache Form haben...

https://www.math.uni-bielefeld.de/~sek/top/leit/alg2.htm

##### **Lie Gruppe**

* eine Lie-Gruppe ist eine mathematische Struktur, die zur Beschreibung von kontinuierlichen Symmetrien verwendet wird. 

* Formal handelt es sich bei einer Lie-Gruppe um eine Gruppe, die als differenzierbare Mannigfaltigkeit aufgefasst werden kann, sodass die Gruppenverknüpfung und Inversenbildung kompatibel mit dieser glatten Struktur sind.

* Eine Lie-Gruppe ist eine [glatte reelle Mannigfaltigkeit](https://de.m.wikipedia.org/wiki/Differenzierbare_Mannigfaltigkeit#Glatte_Mannigfaltigkeit), die zusätzlich die Struktur einer Gruppe besitzt, so dass die Gruppenverknüpfung und die Inversion beliebig oft differenzierbar sind. (*Glatte Funktion: Eine glatte Funktion ist eine mathematische Funktion, die unendlich oft differenzierbar (insbesondere stetig) ist. Die Bezeichnung „glatt“ ist durch die Anschauung motiviert: Der Graph einer glatten Funktion hat keine „Ecken“, also Stellen, an denen sie nicht differenzierbar ist.*)

https://de.m.wikipedia.org/wiki/Lie-Gruppe

**Lie-Algebra**

* ist eine algebraische Struktur, die mit einer Lie-Klammer versehen ist, d. h. es existiert eine antisymmetrische Verknüpfung, die die Jacobi-Identität erfüllt. 

* Lie-Algebren werden hauptsächlich zum Studium geometrischer Objekte wie Lie-Gruppen und differenzierbarer Mannigfaltigkeiten eingesetzt.

https://de.m.wikipedia.org/wiki/Lie-Algebra

##### **Galoistheorie**

https://de.wikipedia.org/wiki/Galoistheorie

#### **Arten an Gruppen**

![cc](https://raw.githubusercontent.com/deltorobarba/repo/master/groups.png)

https://de.m.wikipedia.org/wiki/Präsentation_einer_Gruppe

##### **Finite Simple Groups**

**Simple Group**

https://youtu.be/jhVMBXl5jTA

* Simple Groups are the fundamental building blocks of finite groups (just like Prime numbers are fundamental building blocks in number theory)

* Just as you can factor integers into prime numbers, you can break apart some groups into a direct product of simpler groups.

*  **a simple group is a nontrivial group whose only normal subgroups are the trivial group and the group itself.**

* **Jede Gruppe hat sich selbst und die nur das neutrale Element enthaltende Menge als Normalteiler.** Damit stellt sich die Frage, welche Gruppen keine weitere Normalteiler besitzen. Bei diesen handelt es sich per definitionem gerade um die einfachen Gruppen.

  * Eine Gruppe $G$ heisst einfach, falls sie als Normalteiler nur $G$ und $\{e\}$ mit dem neutralen Element $e$ hat. 
  * Außerdem wird zusătzlich $G \neq\{e\}$ gefordert, wonach man knapper sagen kann: 
  * **Eine Gruppe heißt einfach, wenn sie genau zwei Normalteiler besitzt.**

* A group that is not simple can be broken into two smaller groups, namely a nontrivial [normal subgroup](https://en.wikipedia.org/wiki/Normal_subgroup) and the corresponding quotient group. This process can be repeated, and for finite groups one eventually arrives at uniquely determined simple groups, by the [Jordan–Hölder theorem (Composition series)](https://en.wikipedia.org/wiki/Composition_series).

* The complete classification of finite simple groups, completed in 2004, is a major milestone in the history of mathematics.

https://en.wikipedia.org/wiki/Simple_group

https://de.wikipedia.org/wiki/Einfache_Gruppe_(Mathematik)

**Finite Groups**

* Eine Gruppe ($G$,*) heißt endliche Gruppe, wenn $G$ eine endliche Menge ist, also eine endliche Anzahl von Elementen hat.

* Die Annahme der Endlichkeit ermöglicht ein vereinfachtes Axiomensystem

Ein Paar $(G, *)$ mit einer endlichen Menge $G$ und einer inneren zweistelligen Verknüpfung $*: G \times G \rightarrow G$ heißt Gruppe, wenn folgende Axiome erfüllt sind:

* Assoziativität: Für alle Gruppenelemente $a, b, c$ gilt $(a * b) * c=a *(b * c)$,

* [Kürzungsregel](https://de.m.wikipedia.org/wiki/Kürzbarkeit): Aus $a * x=a * x^{\prime}$ oder $x * a=x^{\prime} * a$ folgt $x=x^{\prime}$

Aus der Kürzungsregel folgt, dass die Links- und Rechtsmultiplikationen $x \mapsto a * x$ und $x \mapsto x * a$
injektiv sind, woraus wegen der Endlichkeit auch die Surjektivität folgt. Daher gibt es ein $x$ mit
$a * x=a,$ was zur Existenz des neutralen Elementes $e$ führt, und dann ein $x$ mit $a * x=e$, was
die Existenz der inversen Elemente zeigt.

https://de.m.wikipedia.org/wiki/Endliche_Gruppe

**Finite Simple Groups**

consists of 18 infinite families and 26 sporadic groups, from which 1 is the [monstergroup](https://www.youtube.com/watch?v=mH0oCDa74tE&list=LL&index=3&t=702s)

https://en.m.wikipedia.org/wiki/Classification_of_finite_simple_groups

[**2004: Classification of Quasithin group**](https://en.wikipedia.org/wiki/Quasithin_group)

* Endliche einfache Gruppen gelten in der Gruppentheorie als die Bausteine der [endlichen Gruppen](https://de.m.wikipedia.org/wiki/Endliche_Gruppe).

* Die endlichen einfachen Gruppen spielen für die endlichen Gruppen eine ähnliche Rolle wie die Primzahlen für die natürlichen Zahlen: Jede endliche Gruppe lässt sich in ihre einfachen Gruppen „zerteilen“ (für die Art der Eindeutigkeit siehe den Satz von Jordan-Hölder). 

* Die Rekonstruktion einer endlichen Gruppe aus diesen ihren „Faktoren“ ist aber nicht eindeutig. 

* Es gibt jedoch keine „noch einfacheren Gruppen“, aus denen sich die endlichen einfachen Gruppen konstruieren lassen.

Obwohl die endlichen einfachen Gruppen seit 1982 als vollständig klassifiziert galten, schlossen Mathematiker um Aschbacher die Klassifikation erst im Jahre 2002 mit einem 1200 Seiten langen Beweis ab:

* Fast alle dieser Gruppen lassen sich einer von 18 Familien endlicher einfacher Gruppen zuordnen.

* Es existieren 26 Ausnahmen. Diese Gruppen werden als **sporadische Gruppen** bezeichnet (Zu den sporadischen Gruppen zählen die Conway-Gruppe, das Babymonster und die **Monstergruppe** (mit fast 1054 Elementen die größte sporadische Gruppe).

https://de.m.wikipedia.org/wiki/Endliche_einfache_Gruppe

https://de.m.wikipedia.org/wiki/Monstergruppe

https://de.m.wikipedia.org/wiki/Sporadische_Gruppe

##### **Trivial Group**

https://de.m.wikipedia.org/wiki/Liste_kleiner_Gruppen

* Die triviale Gruppe ist in der Gruppentheorie eine Gruppe, deren Trägermenge genau ein Element enthält. Die triviale Gruppe ist bis auf Isomorphie eindeutig bestimmt. Jede Gruppe enthält die triviale Gruppe als Untergruppe.

Die triviale Gruppe $(\{e\}, *)$ ist eine Gruppe, die aus der einelementigen Menge $\{e\}$ besteht und versehen ist mit der einzig möglichen Gruppenoperation

$
e * e=e
$

Das Element $e$ ist damit das neutrale Element der Gruppe.

Alle trivialen Gruppen sind zueinander isomorph. Beispiele für triviale Gruppen sind:

* die zyklische Gruppe $C_{1}$ vom Grad 1

* die alternierende Gruppe $A_{2}$ vom Grad 2

* die symmetrische Gruppe $S_{1}$ einer einelementigen Menge


https://de.m.wikipedia.org/wiki/Triviale_Gruppe

##### **Monstergruppe**

https://www.quantamagazine.org/mathematicians-chase-moonshine-string-theory-connections-20150312/

##### **Cyclic Groups C**

* A group G is cyclic if it‘s generated by a single element G = <x>
* Let G be a group with operation * and pick x element G
* What‘s the smallest subgroup of G that contains x ?
    * Its inverse x -1
    * It‘s identity element 1 (for multiplication)
    * All powers of x (squared etc) and powers of inverse of c
* <x> = { ..., x -4, x -3, x -2, x -1, 1, x, x 2, x 3,.. } DIE ziffern sind hier hochgestellt als potenzen !!
* If G = <x> for some x, then we call G a cyclic group, or: if G contains an element ‚x‘ such that G equals the group generated by ‚x‘, then we say G is a cyclic group
* And for group H under operation + pick y element of H, group generated by y = smallest subgroup of H containing y. <y> = {.., -3y, -2y, -y, 0, 2y, 3y, ..}
* Examples: Integers are a cyclic group! And specifically an infinite cyclic group
    * Integers under addition,
    * Claim: Z = <1>
    * <1> = { .., -4, -3, -2, -1, 0, 1, 2, 3, ..}
* Finite cyclic group: Integers mod n under addition
    * Elements: {0, 1, 2, 3... , n -1}
    * The group generated by 1 repeats itself. It cycles through the numbers 0 through N -1 over and over.
    * It‘s written like this: Integers mod n: Z / n Z
    * This will makes sense once studied quotient groups
* All cyclic groups:
    * Infinite: Z, +
    * Finite: Z / nZ, + with: Z, Z/2Z, Z/3Z, Z/4Z,..
    * Trivial group: {e}

![alternativer Text](https://raw.githubusercontent.com/deltorobarba/repo/master/finitecyclicgroups1.png)

![alternativer Text](https://raw.githubusercontent.com/deltorobarba/repo/master/finitecyclicgroups2.png)

* Why are they so important? „Fundamental Theorem of Finitely Generated Abelian Groups“
* Means: any abelian group, that is finitely generated can be broken apart into a finite number of cyclic groups
* And every cyclic group is either integers, or integers mod N
* So cyclic groups are fundamental building blocks for finitely generated abelian groups

##### **Alternierende Gruppe A**

https://de.m.wikipedia.org/wiki/Alternierende_Gruppe

##### **Symmetrische Gruppen S**

1. S3 = Group of Permutations on a set with 3 elements like {1, 2, 3} = 1,2,3 and 2,3,1, and 3,1,2 etc.

2. S3 has n! = 3! = 9 elements. A symmetric group is a finite group with n factorial elements

3. The order of Sn is n factorial |Sn| = n!

Every finite group is a subgroup of a symmetric group ! ([Cayley's theorem](https://en.wikipedia.org/wiki/Cayley%27s_theorem))

* How to combine 2 permutations? A permutation acts like a function, like 1, 2, 3 replaced with 2,3,1. 
* It's a bijection from the set f{1,2,3} $\,\to\,$ {1,2,3} with
  * f(1) = 2
  * f(2) = 3
  * f(3) = 1
* Treating group as function allows to define group operation. for example multiplication and s3 is just function composition
* **except for S1 and S2, all symmetric groups are non abelian, means they are not commutative**. This means if you multiply two permutations of a symmetric group in a reverse order, you get the reversed result, not the same.

Symmetry Groups of Triangles

* We introduce the connection between geometric figures and abstract algebra by showing how you can associate a group with triangles.  
* **The more symmetric the triangle, the larger the group. ** 
* We illustrate this by finding the group of symmetries for equilateral, isosceles and scalene triangles.
* for example take a trianle, do nothing (identity element) and do a couple of transformations (rotate, flip etc)
  * **6 group elements**: identity e, r for rotate once, r<sup>2</sup> for rotate twice, f for flip, rf for rotate and flip, r<sup>2</sup>f rotate twice and flip.
  * rotate three times gives same position, so it's identity element r<sup>3</sup> = e bzw. |r| = 3
  * And flipping twice is also an identity f<sup>2</sup> = e bzw. |f| = 2
  * rotate twice clockwise a triangle gives the same result as roatte once counterclockwise r<sup>-1</sup> = r<sup>2</sup>
* Nimmt man hingegen kein gleichseitiges Dreieck, sondern Dreiecke, die gestreckt sind, ergeben sich weniger Moglichkeiten der Rotation und Flipping, so dass man das Dreieck wieder in die gleiche Form versetzen kann. Im aeussersten Fall nur noch das Identity Element.
* Daher: The more symmetric the triangle, the larger the group. 

https://www.youtube.com/watch?v=3aNeCWRjh8I&list=PLi01XoE8jYoi3SgnnGorR_XOW3IcK-TP6&index=16

https://de.m.wikipedia.org/wiki/Symmetrische_Gruppe

https://de.m.wikipedia.org/wiki/S3_(Gruppe)

##### **Didiergruppe D**

https://de.m.wikipedia.org/wiki/Diedergruppe

##### **Quaternionengruppe Q8**

https://de.m.wikipedia.org/wiki/Quaternionengruppe

##### **Dihedral Group**

![cc](https://raw.githubusercontent.com/deltorobarba/repo/master/dihedral.png)

##### **Matrix Groups**

$
\begin{array}{|l|c|c|}
\hline & \text { Finite Groups } & \text { Infinite Groups } \\
\hline \text { Abelian Groups } & \text { Integers mod } n & \mathbb{Z}, \mathbb{Q}, \mathbb{R}, \mathbb{C} \text { under }+ \\
\hline \text { Non-Abelian Groups } & S_{n} \text { for } n>2 & \text { Matrices } \\
\hline
\end{array}
$

* Matrices are a great example of infinite, nonabelian groups.  Here we introduce matrix groups with an emphasis on the general linear group and special linear group.  The general linear group is written as GLn(F), where F is the field used for the matrix elements.  The most common examples are GLn(R) and GLn(C).  Similarly, the special linear group is written as SLn.


* Real matrices under multiplication, n by n square matrices (for non square matrices you can find two elements that can not be multiplied together). Requirements of a group:
  * **Identity**: I = nxn identity matrix
  * **Associativity**: yes
  * Just each matrix needs to have an **inverse** (a non-zero determinant: for M to have an inverse, det(M) ≠ 0
  * This is a group, the general linear group!

https://www.youtube.com/watch?v=AJTRwhSZJWw&list=PLi01XoE8jYoi3SgnnGorR_XOW3IcK-TP6&index=20

#### **3D Rotation Group**

https://en.m.wikipedia.org/wiki/3D_rotation_group

#### **Orthogonal Groups & SO(n)**

https://en.wikipedia.org/wiki/Orthogonal_group

https://en.wikipedia.org/wiki/SO(8)

##### **Topologische Gruppe**

https://de.wikipedia.org/wiki/Topologische_Gruppe

##### **Direct product of groups (from simple groups)**

* You can piece them together to create larger, more complex groups. One way is the direct product of groups.

* For example combine two groups G1 and G2 (no matter finite or infinite, abelian or non-abelian) into a larger group via the direct product. Operation is done component-wise.

* If any Group is non abelian, then the direct product will be non abelian as well.

* **The direct product is a useful tool for breaking some groups into simpler groups (not all!).** This is because there are many groups which are NOT direct products of simpler groups. But there are other tools for deconstructing groups.

https://www.youtube.com/watch?v=rXLz8TdckWo&list=PLi01XoE8jYoi3SgnnGorR_XOW3IcK-TP6&index=21

##### **Gruppenoperation**

https://de.wikipedia.org/wiki/Gruppenoperation

##### **Verknüpfungstafel**

https://de.wikipedia.org/wiki/Verknüpfungstafel

## **Ringe**

https://youtu.be/_RTHvweHlhE

Watch Polynomring: https://www.youtube.com/watch?v=9fh1QK2yR3g&t=756s

##### **Ring und kommutativer Ring**

https://de.m.wikipedia.org/wiki/Ring_(Algebra)

https://en.m.wikipedia.org/wiki/Ring_(mathematics)

Ein Ring ist eine Menge R mit **zwei inneren binären Verknüpfungen** „+“ und „∙“, sodass gilt:
1. **Addition: (R, +) ist eine abelsche Gruppe**

* Addition is associative and commutative;

* There is an additive identity, zero;

* Every element has an additive inverse;

2. **Multiplikation: (R, ∙) ist eine Halbgruppe**, das bedeutet:

* Halbgruppe in der Multiplikation im Ring: **nur nur die Assoziativität, aber keine Inverse, neutrales element oder kommutativität**) 

* Das bedeutet: -> Sowohl Ringe als auch Körper verlangen, dass bzgl. der Addition eine kommutative Gruppe vorliegt (abelsch!). Bei der Multiplikation erfolgt der Übergang vom Ring zum Körper durch die Verschärfung der Forderungen

* Unlike a field, a ring is not required to have multiplicative inverses, and the multiplication is not required to be commutative. A good example of a ring is the set of all n×n matrices under the operations of matrix addition and matrix multiplication. The integers Z also form a ring under the operations of addition and multiplication.

3. **Die Distributivgesetze a*(b+c)=a*b+a*c und (a+b)*c = a*c+b*c sind für alle a,b,c ε $R$ erfüllt.**

4. **Das neutrale Element 0 von (R, +) heißt Nullelement von R.**

**Ein Ring heißt kommutativ**, falls er bezüglich der Multiplikation kommutativ ist (Ein Ring heißt kommutativ, falls er bezüglich der Multiplikation kommutativ ist, ansonsten spricht man von einem nicht-kommutativen Ring.)

Beispiele:

* 2×2 Real matrices.

* Das wichtigste Beispiel eines Ringes sind die Integers / ist die Menge (􏰁$\mathbb Z$,+,∙) der ganzen Zahlen mit der üblichen Addition und Multiplikation. Es handelt sich dabei um einen nullteilerfreien kommutativen Ring mit Einselement, also einen Integritätsring.

* the Integers modulo some Natural number greater than one;

* Ebenso bildet ($\mathbb Q$,+,∙) der rationalen Zahlen mit der üblichen Addition und Multiplikation einen Ring. Da in diesem Fall nicht nur ($\mathbb Q$,+), sondern auch ($\mathbb Q$ \ {0},∙) eine abelsche Gruppe bildet, liegt sogar ein Körper vor; es handelt sich dabei um den Quotientenkörper des Integritätsringes (􏰁$\mathbb Z$,+,∙).

* Kein Ring ist die Menge ($\mathbb N$􏰀,+,∙) der natürlichen Zahlen mit der üblichen Addition und Multiplikation, da die Addition über den natürlichen Zahlen nicht invertierbar ist.

https://www.quora.com/What-are-the-differences-between-rings-and-fields

https://en.m.wikipedia.org/wiki/Ring_theory

##### **Halbring und kommutativer Halbring**

* Ein Halbring ist die Verallgemeinerung der algebraischen Struktur eines Ringes, in der die **Addition nicht mehr eine kommutative Gruppe, sondern nur noch eine kommutative Halbgruppe sein muss** (mit Abgeschlossenheit und Assoziativität, aber nicht: Neutral (identity element), inverse, kommunitativ).

* Ein Halbring (engl.: Semiring) ist eine algebraische Struktur $(H,+, \cdot)$ mit einer (nichtleeren) Menge $H$ und mit zwei zweistelligen Verknüpfungen $+: H \times H \rightarrow H$ (Addition) und $\because H \times H \rightarrow H$ (Multiplikation), für die gilt:

1. $(H,+)$ ist eine kommutative Halbgruppe.

2. $(H, \cdot)$ ist eine Halbgruppe.

3. Es gelten die Distributivgesetze, d. h. für alle $a, b, c \in H$ gilt $(a+b) \cdot c=a \cdot c+b \cdot c \quad$ sowie $\quad c \cdot(a+b)=c \cdot a+c \cdot b$

Ist auch $(H, \cdot)$ kommutativ, so spricht man von einem kommutativen Halbring.

Beispiele

* $(\mathbb{N},+, 0, \cdot, 1)$ Die Menge der natürlichen Zahlen mit der Addition und der Multiplikation zusammen und mit einem Nullelement und einem Einselement als neutrale Elemente ist ein kommutativer Halbring.

* $\left(\mathbb{Q}_{+},+, 0, \cdot, 1\right)$ ist sogar ein Halbkörper.

* $(\mathbb{R} \cup\{\infty\}, \min , \infty,+, 0),$ die sogenannte Min-Plus-Algebra (**tropische Geometrie!!!**) https://de.m.wikipedia.org/wiki/Max-Plus-Algebra bzw.https://de.wikipedia.org/wiki/Tropische_Geometrie#Tropischer_Halbring

* Für jede Menge $X$ ist die Potenzmenge $(\mathcal{P}(X), \cup, \emptyset, \cap, X)$ ein Halbring.

* Allgemeiner ist jede Boolesche Algebra ein Halbring.

https://de.m.wikipedia.org/wiki/Halbring_(Algebraische_Struktur)

##### **Ring mit Eins (unitärer Ring)**

* Hat die Halbgruppe $R,\cdot$ ein (beidseitiges) neutrales Element 1, ist also ein Monoid, dann nennt man $R,+,\cdot$ einen Ring mit Eins oder unitären Ring. 

* Ringe mit nur links- oder nur rechtsneutralem Element gelten in der Ringtheorie nicht als unitär.

##### **Nullring**

* bis auf Isomorphie eindeutig bestimmter Ring, der nur aus dem Nullelement besteht

* Der Nullring oder triviale Ring ist in der Mathematik der bis auf Isomorphie eindeutig bestimmte Ring, der nur aus dem Nullelement besteht. Das Nullelement ist damit zugleich das Einselement des Rings. 

* Der Nullring besitzt eine Reihe besonderer Eigenschaften, so ist er beispielsweise der einzige Ring, in dem jedes Element eine Einheit ist, und der einzige Ring mit Eins, in dem es kein maximales Ideal gibt. In der Kategorie der Ringe mit Eins ist der Nullring terminales Objekt und in der Kategorie aller Ringe das Nullobjekt.

Der Nullring $(\{0\},+, \cdot)$ ist ein Ring bestehend aus der einelementigen Menge \{0\} (Singleton) versehen mit der einzig möglichen Addition gegeben durch

$
0+0=0
$

und der einzig möglichen Multiplikation gegeben durch

$
0 \cdot 0=0
$

Das Element 0 ist also zugleich das Nullelement und das Einselement des Rings.

* In der Kategorie der Ringe mit Eins ist der Nullring terminales Objekt, das heißt von jedem Ring gibt es genau einen Morphismus in den Nullring. Weiterhin ist jeder Morphismus aus dem Nullring heraus bereits ein Isomorphismus.

* In der Kategorie aller Ringe ist der Nullring sogar das Nullobjekt.

https://de.m.wikipedia.org/wiki/Nullring

##### **Ideal**

* In der abstrakten Algebra ist ein Ideal eine Teilmenge eines Rings, die das Nullelement enthält und abgeschlossen gegenüber Addition und Subtraktion von Elementen des Ideals sowie abgeschlossen gegenüber Multiplikation mit beliebigen Ringelementen ist. 

* Beispielsweise sind Summe und Differenz zweier gerader Zahlen wieder gerade und zudem ist das Produkt einer geraden Zahl mit einer beliebigen ganzen Zahl ebenfalls gerade. Zudem ist die 0 als additiv Neutrales gerade. Das heißt, die Menge der geraden Zahlen ist ein Ideal im Ring der ganzen Zahlen.

* Es gibt auch für nichtkommutative Ringe sogenannte Links-, Rechtsideale und zweiseitige Idealen.

https://de.m.wikipedia.org/wiki/Ideal_(Ringtheorie)

##### **Quotientenkörper**

* In der Algebra ist der Quotientenkörper eines Rings (mit bestimmten Eigenschaften) eine **Obermenge dieses Rings**, auf welche die Addition und die Multiplikation des Rings fortgesetzt werden und in der jedes Element außer 0 ein multiplikatives Inverses besitzt. 

* Das prominenteste Beispiel ist der **Körper der rationalen Zahlen als Quotientenkörper des Rings der ganzen Zahlen**.

* Eine Verallgemeinerung des Konzepts für nicht notwendigerweise nullteilerfreie Ringe ist durch die Lokalisierung gegeben.

https://de.m.wikipedia.org/wiki/Quotientenkörper

## **Körper (Field)**

https://youtu.be/KCSZ4QhOw0I

https://de.m.wikipedia.org/wiki/Geordneter_Körper

https://de.m.wikipedia.org/wiki/Körpererweiterung

##### **(Kommutative) Körper**

**Set $F$ with 2 operations: $+$**

* $\langle F,+\rangle$ is a commutative group

* $\left\langle F^{\times}, \cdot\right\rangle$ is a commutative group

* $a \cdot(b+c)=a \cdot b+a \cdot c$

* $(b+c) \cdot a=b \cdot a+c \cdot a$

Fields allow a multiplicative inverse (aka division)

https://www.youtube.com/watch?v=KCSZ4QhOw0I

**Ein Körper ist eine spezielle Form von Ring**:

* **A Field is a Ring whose non-zero elements form a commutative Group under multiplication (In short a field is a commutative ring with unity with all its non zero elements having multiplicative inverse.)**

* Ein kommutativer unitärer Ring, der nicht der Nullring ist, heißt ein Körper, wenn in ihm jedes von Null verschiedene Element multiplikativ invertierbar ist.
Anders formuliert, ist ein Körper ein kommutativer unitärer Ring K, in dem die Einheitengruppe K* gleich K \ {0}, also maximal groß, ist.

* Ein kommutativer unitärer Ring, der nicht der Nullring ist, ist ein Körper, wenn in ihm jedes von Null verschiedene Element ein Inverses bezüglich der Multiplikation besitzt. Anders formuliert, ist ein Körper ein kommutativer unitärer Ring $K$, in dem die Einheitengruppe $K^{*}$ gleich $K \backslash\{0\}$ ist. 


https://de.m.wikipedia.org/wiki/Körper_(Algebra)

https://science.jrank.org/pages/2709/Field.html

Ein Tripel (K,+,•), bestehend aus einer Menge K und zwei binären Verknüpfungen „+“ und „•“ (die üblicherweise Addition und Multiplikation genannt werden), ist genau dann ein Körper, wenn folgende Eigenschaften erfüllt sind:

* $(K,+)$ ist eine abelsche Gruppe (mit Neutralelement 0)

* $(K \backslash\{0\}, •)$ ist eine abelsche Gruppe (mit Neutralelement 1)

* $a \cdot(b+c)=a \cdot b+a \cdot c$ und $(a+b) \cdot c=a \cdot c+b \cdot c$ (Distributivgesetz)

Additive Eigenschaften:

* $a+(b+c)=(a+b)+c$ (Assoziativgesetz)

* $a+b=b+a$ (Kommutativgesetz)

* Es gibt ein Element $0 \in K$ mit $0+a=a$ (neutrales Element)

* Zu jedem $a \in K$ existiert das additive Inverse $(-a)$ mit $(-a)+a=0$

Multiplikative Eigenschaften:

* $\cdot a \cdot(b \cdot c)=(a \cdot b) \cdot c$ (Assoziativgesetz)

* $a \cdot b=b \cdot a$ (Kommutativgesetz)

* Es gibt ein Element $1 \in K$ mit $1 \cdot a=a$ (neutrales Element), und es ist $1 \neq 0$.

* Zu jedem $a \in K \backslash\{0\}$ existiert das multiplikative Inverse $a^{-1}$ mit $a^{-1} \cdot a=1$

Zusammenspiel von additiver und multiplikativer Struktur:

* $a \cdot(b+c)=a \cdot b+a \cdot c$ (Links-Distributivgesetz) 

* Das Rechts-Distributivgesetz $(a+b) \cdot c=a \cdot c+b \cdot c$ folgt dann aus den übrigen Eigenschaften:
$(a+b) \cdot c=c \cdot(a+b)=c \cdot a+c \cdot b=a \cdot c+b \cdot c$

##### **Körper vs Schiefkörper**

* Eine Menge K mit zwei binären Operationen + und ⋅ heißt Schiefkörper, wenn K ein Ring ist und K∖{0} bzgl. der Multiplikation eine Gruppe bildet (Ringe sind normalerweise Halbgruppen, dh. bezüglich Multiplikation nur nur die Assoziativität zählt, aber keine Inverse, neutrales element oder kommutativität).

* K heißt Körper, wenn K Schiefkörper ist und 
K∖{0} bzgl. der Multiplikation eine kommutative Gruppe (=Abelsch) bildet.

**Es gelten die folgenden Zusammenhänge:**

* Jeder Körper ist ein Schiefkörper
* Jeder Körper ist ein kommutativer Ring
* Jeder Schiefkörper ist ein unitären Ring
* Jeder unitäre Ring ist ein Ring

**Achtung**

Man nennt die Elemente im Körper nicht Vektoren, sondern Skalare. Über dem Skalarkörper betrachtet man einen Vektorraum und dessen Elemente heißen Vektoren.

Eigenschaften (beginnend mit denen eines Ringes):

* Addition is associative and commutative;

* There is an additive identity, zero;

* Every element has an additive inverse;

* Multiplication is associative;

* Multiplication distributes over addition.

In addition a Field has:

* Multiplication is commutative;

* Every non-zero element has a multiplicative inverse.

Beispiele:

* The most familiar form of algebra is the elementary algebra that you learned in high school, namely the algebra of the real numbers. From an abstract point of view, this is the algebra of fields.

* Note that the axioms for a field are precisely the axioms for algebra on the real numbers. As a result, the real numbers R form a field under the usual operations of addition and multiplication. However, the real numbers are not the only possible field. Indeed, you are already familiar with a few other examples:

* set of rational numbers under addition and multiplication. The rational numbers Q form a field under the usual operations of addition and multiplication. In particular, we can add or multiply two elements of Q to obtain another element of Q, and these operations obey all of the axioms listed above.

* The complex numbers C form a field under the commonly defined operations of addition and multiplication. Complex numbers do obey all of the listed axioms for a field, which is why elementary algebra works as usual for complex numbers.

* The Integers modulo a Prime number.

*An example of a set of numbers that is **not a field** is the set of integers. It is an "integral domain." It is not a field because it lacks multiplicative inverses. Without multiplicative inverses, division may be impossible.*

* Both are algebraic objects with a notion of addition and multiplication, **but the multiplication in a field is more specialized**: it is necessarily commutative and every nonzero element has a multiplicative inverse.

##### **Schiefkörper (Divisionsring)**

* Ein **Schiefkörper** oder Divisionsring ist eine algebraische Struktur, die alle Eigenschaften eines Körpers besitzt, außer dass die Multiplikation nicht notwendigerweise kommutativ ist.

* Jeder Schiefkörper ist ein Alternativkörper

https://de.m.wikipedia.org/wiki/Schiefkörper

##### **Alternativkörper**

* Octonions (Octave) sind [Alternativkörper](https://de.m.wikipedia.org/wiki/Alternativkörper) bei denen man auf das Kommutativgesetz und das Assoziativgesetz für die Multiplikation verzichtet.

* Jeder Schiefkörper ist ein Alternativkörper, jeder Alternativkörper ist zugleich ein Links- und ein Rechtsquasikörper. Endliche Alternativkörper sind stets Körper. (→ Siehe dazu auch: Moufangebene).



##### **Körpererweiterung**

https://de.wikipedia.org/wiki/K%C3%B6rpererweiterung

##### **Exkurs: Geordneter Körper**

* Ein geordneter Körper (auch angeordneter Körper genannt) ist ein Körper zusammen mit einer totalen Ordnung „≤“, die mit Addition und Multiplikation verträglich ist. Das bekannteste Beispiel ist der Körper der reellen Zahlen. 

* Körper der Charakteristik p>0 können nicht strukturverträglich angeordnet werden. 

* Ein wichtiges Beispiel für einen Körper der Charakteristik 0, der auch nicht strukturverträglich angeordnet werden kann, ist der Körper der komplexen Zahlen.

* Ein geordneter Körper heißt ordnungsvollständig, wenn jede beschränkte Teilmenge des Körpers ein Infimum und Supremum hat.

https://de.m.wikipedia.org/wiki/Geordneter_Körper

## **Moduln und Vektorräume**

#### **Moduln**

* Ein Modul ist ein n-dimensionaler Ring.

* Ein Modul ist eine algebraische Struktur, die eine Verallgemeinerung eines Vektorraums darstellt.

* **A module is similar to a vector space, except that the scalars are only required to be elements of a ring. (Gilt NICHT multiplikative Inverse und multiplikative Kommuntativität)**

* For example, the set Zn of n-dimensional vectors with integer entries forms a module, where “scalar multiplication” refers to multiplication by integer scalars.

Folgende Zahlenbereiche sind additive Gruppen und damit $\mathbb {Z}$ -Moduln:

* die ganzen Zahlen $\mathbb {Z}$ selbst

* die rationalen Zahlen $\mathbb {Q}$ 

* die reellen Zahlen $\mathbb {R}$ 

* die algebraischen Zahlen $\mathbb A$ bzw. $\mathbb A$ $\cap$ $\mathbb R$

* die komplexen Zahlen $\mathbb {C}$


https://de.m.wikipedia.org/wiki/Modul_(Mathematik)

**Basis eines Modul**

* Der Begriff der Basis eines Moduls ist im mathematischen Teilgebiet der Algebra eine Verallgemeinerung des Begriffes der Basis eines Vektorraumes. 

* Wie bei diesen wird eine Basis eines Moduls als linear unabhängiges Erzeugendensystem definiert; im Gegensatz zu Vektorräumen besitzt allerdings nicht jeder Modul eine Basis.

https://de.m.wikipedia.org/wiki/Basis_(Modul)

https://de.m.wikipedia.org/wiki/Basis_(Vektorraum)

#### **Vektorraum (Lineare Algebra)**

###### **Module vs Vector Space**

1. Module = Vector Space with a **ring** of scalars

2. Vector Space = Module with a **field** of scalars

**Vector Space**

* Abelian group $V$ of vectors

* Field $F$ of "scalars"

* $f \cdot v$ is a "scaled vector"

Distributive properties:
$f \cdot\left(v_{1}+v_{2}\right)=f \cdot v_{1}+f \cdot v_{2}$
$\left(f_{1}+f_{2}\right) \cdot v=f_{1} \cdot v+f_{2} \cdot v$

Associative property:

$\left(f_{1} \cdot f_{2}\right) \cdot v=f_{1} \cdot\left(f_{2} \cdot v\right)$
$1 \cdot v=v$

**(Left or Right) Module**

* Abelian group $M$ of "elements"

* Ring $R$ of "scalars"

* $r \cdot m$ is a "scaled element"

Distributive properties:

$r \cdot\left(m_{1}+m_{2}\right)=r \cdot m_{1}+r \cdot m_{2}$
о $\left(r_{1}+r_{2}\right) \cdot m=r_{1} \cdot m+r_{2} \cdot m$

Associative property:

$\left(r_{1} \cdot r_{2}\right) \cdot m=r_{1} \cdot\left(r_{2} \cdot m\right)$
$1 \cdot m=m$

**Example of a Module:**

Group: $M=\mathbb{R}^{3}=\{(x, y, z) \mid x, y, z \in \mathbb{R}\}$ under $+$

Scalar Ring: $R=\left\{\left(\begin{array}{lll}a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33}\end{array}\right) \mid a_{i j} \in \mathbb{R}\right\}$

$R$ is not a field:
* Not every matrix is invertible 
* Not commutative 
* Does have an identity: $\left(\begin{array}{cc}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{array}\right)$

https://youtu.be/IvukAijXgLE

###### **Linear Abbildung**

https://de.wikipedia.org/wiki/Bilinearform#

https://en.wikipedia.org/wiki/Multilinear_algebra

https://de.wikipedia.org/wiki/Determinante

https://de.m.wikipedia.org/wiki/Eigenwertproblem

https://de.m.wikipedia.org/wiki/Eigenraum

https://de.m.wikipedia.org/wiki/Lineare_Algebra

https://de.m.wikibooks.org/wiki/Mathematik:_Lineare_Algebra

https://mathepedia.de/Lineare_Abbildungen.html

* Lineare Abbildung zwischen Vektorräumen

* Erfüllt Bedingung der Homogenität und der Additivität (siehe unter Morphismen das Thema "Vektorraumhomomorphismus")

[Numerische Verfahren:](https://de.m.wikipedia.org/wiki/Liste_numerischer_Verfahren) lineare Gleichungssysteme, Eigenwerte etc

**Linearkombination**

https://de.m.wikipedia.org/wiki/Linearkombination

**Assoziative Algebra**

* Es handelt sich um eine algebraische Struktur, die den Begriff des Vektorraums bzw. des Moduls dahingehend erweitert, dass zusätzlich zur Vektoraddition eine **assoziative Multiplikation** als innere Verknüpfung definiert wird.

https://de.m.wikipedia.org/wiki/Assoziative_Algebra

###### **Vektorraum**

3 most important pillars of linear algebra: https://www.youtube.com/watch?v=Ww_aQqWZhz8&t=194s

**Konkrete form of vectors don't matter (matrices, vectors, functions, pie transforms etc). All what matters are the 8 axioms which define a vector space:**

![cc](https://raw.githubusercontent.com/deltorobarba/repo/master/vectorspace_axioms.png)

https://www.youtube.com/watch?v=TgKwz5Ikpc8&list=WL&index=33&t=638s

https://de.m.wikipedia.org/wiki/Basis_(Vektorraum)

Ein Vektorraum u ̈ber einem Körper $\mathbb K$ ist eine abelsche Gruppe mit der Eigenschaft, dass es zu jedem Element k von $\mathbb K$ (”Skalar“) eine einstellige Operation (”Skalarmultiplikation“ )

Oder anders: 
* Körper: Plus oder Mal im Körper: zwei Körperelemente, und dann kommt wieder Körperelement heraus
* Vektorraum: (Mal heisst nur strecken und stauchen = Skalarmultiplikation: Vektor multipliziert mit Körperelement

https://en.m.wikipedia.org/wiki/Algebra_over_a_field

https://de.m.wikipedia.org/wiki/Algebra_über_einem_Körper

* Ein Vektorraum ist ein n-dimensionaler Körper.

* A vector space is an algebraic structure with operations of addition and multiplication by scalars. Gilt zusätzlich multiplikative Inverse und multiplikative Kommuntativität

* The scalars are required to be elements of a field, such as the real numbers R. The basic example of a vector space is the set Rn of all vectors with n entries.

* Ein Vektorraum oder linearer Raum ist eine algebraische Struktur, die in vielen Teilgebieten der Mathematik verwendet wird. 

* Vektorräume bilden den zentralen Untersuchungsgegenstand der linearen Algebra. 

* Die Elemente eines Vektorraums heißen Vektoren. 

* Sie können addiert oder mit Skalaren (Zahlen) multipliziert werden, das Ergebnis ist wieder ein Vektor desselben Vektorraums.

* Die **Skalare, mit denen man einen Vektor multiplizieren kann, stammen aus einem Körper**. Deswegen ist ein Vektorraum immer ein Vektorraum über einem bestimmten Körper. Sehr oft handelt es sich dabei um den Körper 
$\mathbb {R}$ der reellen Zahlen oder den Körper 
$\mathbb {C}$ der komplexen Zahlen. Man spricht dann von einem reellen Vektorraum bzw. einem komplexen Vektorraum.

https://de.m.wikipedia.org/wiki/Vektorraum

**K-Algebra (Algebra über einem Körper)**

* ist ein Vektorraum über einem Körper K, der um eine mit der Vektorraumstruktur verträgliche Multiplikation erweitert wurde. 

* Je nach Kontext wird dabei mitunter zusätzlich gefordert, dass die Multiplikation das Assoziativgesetz oder das Kommutativgesetz erfüllt oder dass die Algebra bezüglich der Multiplikation ein Einselement besitzt.

* Allgemeiner kann K ein kommutativer Ring sein, dann ist „Vektorraum“ durch „Modul“ zu ersetzen, und man erhält eine [Algebra über einem kommutativen Ring](https://de.m.wikipedia.org/wiki/Algebra_über_einem_kommutativen_Ring).

https://de.m.wikipedia.org/wiki/Algebra_über_einem_Körper

###### **Orthonormalbasis**

**Orthogonalisieren**: zwei (oder mehr) Vektoren orthogonal zueinander bringen

**Orthonormalisieren**: diese auch noch auf Lange 1 zu normalisieren

* Ziel: Vereinfachung des Rechnens mit Vektoren

* Eine Orthonormalbasis (ONB) oder ein vollständiges Orthonormalsystem (VONS) in den mathematischen Gebieten lineare Algebra und Funktionalanalysis **ist eine Menge von Vektoren aus einem Vektorraum mit Skalarprodukt (Innenproduktraum), welche auf die Länge eins normiert und zueinander orthogonal sind** (daher Ortho-normal-basis) und deren lineare Hülle dicht im Vektorraum liegt. 

* Im endlichdimensionalen Fall ist dies eine Basis des Vektorraums. Im unendlichdimensionalen Fall handelt es sich nicht um eine Vektorraumbasis im Sinn der linearen Algebra.

* Verzichtet man auf die Bedingung, dass die Vektoren auf die Länge eins normiert sind, so spricht man von einer **Orthogonalbasis**.

* Der Begriff der Orthonormalbasis ist sowohl im Fall endlicher Dimension als auch für unendlichdimensionale Räume, insbesondere Hilberträume, von großer Bedeutung.

https://de.wikipedia.org/wiki/Orthonormalbasis

https://de.wikipedia.org/wiki/Gram-Schmidtsches_Orthogonalisierungsverfahren

https://www.youtube.com/watch?v=SLEElig-C9w

###### **Funktionenraum**

https://de.m.wikipedia.org/wiki/Funktionenraum

###### **Folgenraum**

https://de.m.wikipedia.org/wiki/Folgenraum

###### **Polynomräume**

https://de.m.wikipedia.org/wiki/Vektorraum#Polynomr%C3%A4ume

###### **Körpererweiterungen**

https://de.m.wikipedia.org/wiki/Vektorraum#K%C3%B6rpererweiterungen

#### **Matrix Factorization (Decomposition)**

##### **Overview**

* Not to be confused with Matrix factorization of a polynomial.
* In the mathematical discipline of linear algebra, a matrix decomposition or matrix factorization is a factorization of a matrix into a product of matrices. 

* There are many different matrix decompositions; each finds use among a particular class of problems.

https://en.wikipedia.org/wiki/Matrix_decomposition

https://en.wikipedia.org/wiki/Matrix_factorization_of_a_polynomial

##### **LU Decomposition**

**Characteristics of an LU Decomposition**

The LU decomposition is often used to simplify the **solving of systems of linear equations**, such as **finding the coefficients in a linear regression**, as well as in **calculating the determinant and inverse** of a matrix.

* Lower–upper (LU) decomposition or factorization factors a matrix as the product of a lower triangular matrix and an upper triangular matrix. 

* The product sometimes includes a permutation matrix as well. LU decomposition can be viewed as the matrix form of Gaussian elimination. 

* Computers usually solve square systems of linear equations using LU decomposition, and it is also a key step when inverting a matrix or computing the determinant of a matrix.

The **LU decomposition is for square matrices** and decomposes a matrix into L and U components. Let A be a square matrix. An LU factorization refers to the factorization of A, with proper row and/or column orderings or permutations, into two factors – a **lower triangular matrix L** and an **upper triangular matrix U**:

> A = L U

* The LU decomposition is found using an <u>iterative numerical process</u> and **can fail for those matrices that cannot be decomposed or decomposed easily**.

* In the lower triangular matrix all elements above the diagonal are zero, in the upper triangular matrix, all the elements below the diagonal are zero. For example, for a 3 × 3 matrix A, its LU decomposition looks like this:

> $\left[\begin{array}{lll}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{array}\right]=\left[\begin{array}{ccc}
l_{11} & 0 & 0 \\
l_{21} & l_{22} & 0 \\
l_{31} & l_{32} & l_{33}
\end{array}\right]\left[\begin{array}{ccc}
u_{11} & u_{12} & u_{13} \\
0 & u_{22} & u_{23} \\
0 & 0 & u_{33}
\end{array}\right]$

**Underdeterminism & Unit Triangular Matrix**

* Sometimes **equations is [underdetermined](https://en.m.wikipedia.org/wiki/Underdetermined_system)**. In this case any two non-zero elements of L and U matrices are parameters of the solution and can be set arbitrarily to any non-zero value. 

* Therefore, to find the unique LU decomposition, it is **necessary to put some restriction on L and U matrices**. For example, we can conveniently require the lower triangular matrix L to be a **unit triangular matrix** (i.e. set all the entries of its main diagonal to ones). 

**Square matrices**

* Any square matrix A admits an LUP factorization. If A is [invertible](https://en.m.wikipedia.org/wiki/Invertible_matrix), then it admits an LU (or LDU) factorization if and only if all its leading principal [minors](https://en.m.wikipedia.org/wiki/Minor_(linear_algebra)) are nonzero. 

* If A is a singular matrix of rank k, then it admits an LU factorization if the first k leading principal minors are nonzero, although the converse is not true.

* If a square, invertible matrix has an LDU (factorization with all diagonal entries of L and U equal to 1), then the factorization is unique. In that case, the LU factorization is also unique if we require that the diagonal of L (or U) consists of ones.

**Symmetric positive definite matrices**

* If A is a symmetric (or [Hermitian](https://en.m.wikipedia.org/wiki/Hermitian_matrix), if A is complex) [positive definite](https://en.m.wikipedia.org/wiki/Definite_symmetric_matrix) matrix, we can arrange matters so that U is the [conjugate transpose](https://en.m.wikipedia.org/wiki/Conjugate_transpose) of L. That is, we can write A as

> A = LL*

* This decomposition is called the **Cholesky decomposition**. The Cholesky decomposition always exists and is unique — provided the matrix is positive definite. 

* Furthermore, computing the Cholesky decomposition is more efficient and [numerically more stable](https://en.m.wikipedia.org/wiki/Numerical_stability) than computing some other LU decompositions.

**General matrices**

* For a (not necessarily invertible) matrix over any field, the exact necessary and sufficient conditions under which it has an LU factorization are known. 

* The conditions are expressed in terms of the ranks of certain submatrices. The Gaussian elimination algorithm for obtaining LU decomposition has also been extended to this most general case.

**Variations of LU Decomposition**

**LU factorization with partial pivoting (LUP Decomposition)**

A variation of this decomposition that is numerically more stable to solve in practice is called the LUP decomposition, or the **LU decomposition with partial pivoting**.

> A = P L U

The rows of the parent matrix are re-ordered to simplify the decomposition process and the **additional P matrix specifies a way to permute the result or return the result to the original order**.

It turns out that a proper permutation in rows (or columns) is sufficient for LU factorization. LU factorization with partial pivoting (LUP) refers often to LU factorization with row permutations only:

> PA = LU

where L and U are again lower and upper triangular matrices, and P is a [permutation matrix](https://en.m.wikipedia.org/wiki/Permutation_matrix)*, which, when left-multiplied to A, reorders the rows of A. It turns out that all square matrices can be factorized in this form, and the factorization is numerically stable in practice. This makes LUP decomposition a useful technique in practice.

*A permutation matrix is a square binary matrix that has exactly one entry of 1 in each row and each column and 0s elsewhere.*

**LU factorization with full pivoting**

An LU factorization with full pivoting involves both row and column permutations:

> PAQ = LU

where L, U and P are defined as before, and Q is a permutation matrix that reorders the columns of A.

**LDU Decomposition**

An LDU decomposition is a decomposition of the form

> A = LDU

where D is a diagonal matrix, and L and U are unitriangular matrices, meaning that all the entries on the diagonals of L and U are one.

Below we required that A be a square matrix, but these decompositions can all be generalized to rectangular matrices as well. In that case, **L and D are square matrices** both of which have the same number of rows as A, and U has exactly the same dimensions as A. Upper triangular should be interpreted as having only zero entries below the main diagonal, which starts at the upper left corner.

![LDU decomposition of a Walsh matrix](https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/LDU_decomposition_of_Walsh_16.svg/640px-LDU_decomposition_of_Walsh_16.svg.png)

*LDU decomposition of a [Walsh matrix](https://en.m.wikipedia.org/wiki/Walsh_matrix)*

**Example**

**Define Matrix**

In [2]:
# LU decomposition
from numpy import array

# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Decompose**

In [3]:
# LU decomposition
from scipy.linalg import lu
P, L, U = lu(A)

In [4]:
print(P)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [5]:
print(L)

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]


In [6]:
print(U)

[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]


**Reconstruct**

In [7]:
B = P.dot(L).dot(U)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [8]:
# Check for differences between both matrices
X = B - A
print(X)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### **QR Decomposition**

* The QR decomposition is for m x n matrices (not limited to square matrices) and decomposes a matrix into Q and R components.

> A = Q R

* Where A is the matrix that we wish to decompose, Q a matrix with the size m x m, and R is an upper triangle matrix with the size m x n.

* **Q is an orthogonal (Q<sup>T</sup> Q = I) or unitary matrix** (Q ∗ Q = I) and **R is an upper triangular matrix**. The QR decomposition is a special case of the [Iwasawa decomposition](https://en.m.wikipedia.org/wiki/Iwasawa_decomposition).

* The QR decomposition is found using an iterative numerical method that can fail for those matrices that cannot be decomposed, or decomposed easily.

* Like the LU decomposition, the QR decomposition is often used to solve systems of linear equations, although is not limited to square matrices.

* By default, the qr function returns the Q and R matrices with smaller or ‘reduced’ dimensions that is more economical. We can change this to return the expected sizes of m x m for Q and m x n for R by specifying the mode argument as ‘complete’, although this is not required for most applications.

Such a decomposition always exists and can be calculated using various algorithms. The best known are

* [Householder transformations](https://de.m.wikipedia.org/wiki/Householdertransformation)
* [Givens rotations](https://de.m.wikipedia.org/wiki/Givens-Rotation)
* [Gram-Schmidtsch's orthogonalization method](https://de.m.wikipedia.org/wiki/Gram-Schmidtsches_Orthogonalisierungsverfahren)

**Define Matrix**

In [ ]:
from numpy import array

# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


**Decompose**

In [ ]:
# QR decomposition
from numpy.linalg import qr
Q, R = qr(A, 'complete')

In [ ]:
print(Q)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]


In [ ]:
print(R)

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


**Reconstruct**

In [ ]:
B = Q.dot(R)
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


##### **Cholesky Decomposition**

The Cholesky decomposition is for square symmetric matrices where all eigenvalues are greater than zero, so-called [positive definite matrices](https://en.wikipedia.org/wiki/Definite_symmetric_matrix). For our interests in machine learning, we will focus on the Cholesky decomposition for real-valued matrices and ignore the cases when working with complex numbers.

> A = LL^T

Where A is the matrix being decomposed, L is the lower triangular matrix and L^T is the transpose of L.

The decompose can also be written as the product of the upper triangular matrix, for example:

> A = U^T . U

* Where U is the upper triangular matrix.

* The Cholesky decomposition is used for solving linear least squares for linear regression, as well as simulation and optimization methods.

* When decomposing symmetric matrices, the Cholesky decomposition is nearly twice as efficient as the LU decomposition and should be preferred in these cases.

* While symmetric, positive definite matrices are rather special, they occur quite frequently in some applications, so their special factorization, called Cholesky decomposition, is good to know about. When you can use it, Cholesky decomposition is about a factor of two faster than alternative methods for solving linear equations.

**Define Matrix**

In [ ]:
from numpy import array

# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


**Decompose**

In [ ]:
# Cholesky decomposition
from numpy.linalg import cholesky
L = cholesky(A)
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


**Reconstruct**

In [ ]:
B = L.dot(L.T)
print(B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


##### **Singular-Value Decomposition (SVD)**

* Matrix decomposition, also known as matrix factorization, involves describing a given matrix using its constituent elements.

* Perhaps the most known and widely used matrix decomposition method is the Singular-Value Decomposition, or SVD. All matrices have an SVD, which makes it more stable than other methods, such as the eigendecomposition. As such, it is often used in a wide array of applications including compressing, denoising, and data reduction.

* The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations simpler.

* For the case of simplicity we will focus on the SVD for real-valued matrices and ignore the case for complex numbers.

> A = U . Sigma . V^T

* Where A is the real m x n matrix that we wish to decompose, U is an m x m matrix, Sigma (often represented by the uppercase Greek letter Sigma) is an m x n diagonal matrix, and V^T is the  transpose of an n x n matrix where T is a superscript.

* The diagonal values in the Sigma matrix are known as the singular values of the original matrix A. The columns of the U matrix are called the left-singular vectors of A, and the columns of V are called the right-singular vectors of A.

* The SVD is calculated via iterative numerical methods. We will not go into the details of these methods. Every rectangular matrix has a singular value decomposition, although the resulting matrices may contain complex numbers and the limitations of floating point arithmetic may cause some matrices to fail to decompose neatly.

* The singular value decomposition (SVD) provides another way to factorize a matrix, into singular vectors and singular values. The SVD allows us to discover some of the same kind of information as the eigendecomposition. However, the SVD is more generally applicable.

* The SVD is used widely both in the calculation of other matrix operations, such as matrix inverse, but also as a data reduction method in machine learning. SVD can also be used in least squares linear regression, image compression, and denoising data.

* The SVD can be calculated by calling the svd() function. The function takes a matrix and returns the U, Sigma and V^T elements. The Sigma diagonal matrix is returned as a vector of singular values. The V matrix is returned in a transposed form, e.g. V.T.

**Define a Matrix**

In [ ]:
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


**Decompose**

In [ ]:
# Calculate Singular-Value Decomposition
from scipy.linalg import svd
U, s, VT = svd(A)

In [ ]:
print(U)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]


In [ ]:
print(s)

[9.52551809 0.51430058]


In [ ]:
print(VT)

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


**Reconstruct**

* The original matrix can be reconstructed from the U, Sigma, and V^T elements.
* The U, s, and V elements returned from the svd() cannot be multiplied directly.
* The s vector must be converted into a diagonal matrix using the diag() function. By default, this function will create a square matrix that is n x n, relative to our original matrix. This causes a problem as the size of the matrices do not fit the rules of matrix multiplication, where the number of columns in a matrix must match the number of rows in the subsequent matrix.
* After creating the square Sigma diagonal matrix, the sizes of the matrices are relative to the original m x n matrix that we are decomposing, as follows:

> U (m x m) . Sigma (n x n) . V^T (n x n)

* Where, in fact, we require:

> U (m x m) . Sigma (m x n) . V^T (n x n)

* We can achieve this by creating a new Sigma matrix of all zero values that is m x n (e.g. more rows) and populate the first n x n part of the matrix with the square diagonal matrix calculated via diag().

In [ ]:
from numpy import diag
from numpy import dot
from numpy import zeros

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


The above complication with the Sigma diagonal only exists with the case where m and n are not equal. The diagonal matrix can be used directly when reconstructing a square matrix, as follows.

In [ ]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd

# define a matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# Singular-value decomposition
U, s, VT = svd(A)
# create n x n Sigma matrix
Sigma = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


**Appendix: SVD for Pseudoinverse**

* The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular matrices where the number of rows and columns are not equal.

* It is also called the the Moore-Penrose Inverse after two independent discoverers of the method or the Generalized Inverse.

* Matrix inversion is not defined for matrices that are not square. When A has more columns than rows, then solving a linear equation using the pseudoinverse provides one of the many possible solutions.

* The pseudoinverse is denoted as A^+, where A is the matrix that is being inverted and + is a superscript. The pseudoinverse is calculated using the singular value decomposition of A:

> A^+ = VD^+U^T

Where A^+ is the pseudoinverse, D^+ is the pseudoinverse of the diagonal matrix Sigma and U^T is the transpose of U.

We can get U and V from the SVD operation.

> A = U . Sigma . V^T

The D^+ can be calculated by creating a diagonal matrix from Sigma, calculating the reciprocal of each non-zero element in Sigma, and taking the transpose if the original matrix was rectangular.



In [ ]:
#          s11,   0,   0
# Sigma = (  0, s22,   0)
#            0,   0, s33

In [ ]:
#        1/s11,     0,     0
# D^+ = (    0, 1/s22,     0)
#            0,     0, 1/s33

The pseudoinverse provides one way of solving the linear regression equation, specifically when there are more rows than there are columns, which is often the case. 

NumPy provides the function pinv() for calculating the pseudoinverse of a rectangular matrix. The example below defines a 4×2 matrix and calculates the pseudoinverse.

In [ ]:
# Pseudoinverse
from numpy import array
from numpy.linalg import pinv

# define matrix
A = array([
	[0.1, 0.2],
	[0.3, 0.4],
	[0.5, 0.6],
	[0.7, 0.8]])
print(A)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]


In [ ]:
# calculate pseudoinverse
B = pinv(A)
print(B)

[[-1.00000000e+01 -5.00000000e+00  1.42385628e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


##### **Rank Factorization**

* given an m × n matrix A of rank r, a rank decomposition or rank factorization of A is a factorization of A of the form A = C F, where C is an m × r matrix and F is an r × n matrix.

* Every finite-dimensional matrix has a rank decomposition

* One can also construct a full rank factorization of A by using its singular value decomposition

##### **Eigendecomposition**

* Eigendecomposition or sometimes spectral decomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way.

##### **Non-negative matrix factorization**

* Non-negative matrix factorization (NMF or NNMF), also non-negative matrix approximation is a **group of algorithms** in multivariate analysis and linear algebra where a matrix V is factorized into (usually) two matrices W and H, with the property that all three matrices have no negative elements. 

* This non-negativity makes the resulting matrices easier to inspect. Also, in applications such as processing of audio spectrograms or muscular activity, non-negativity is inherent to the data being considered. 

* Since the problem is not exactly solvable in general, it is commonly approximated numerically.

![NNMF](https://upload.wikimedia.org/wikipedia/commons/f/f9/NMF.png)

*Illustration of approximate non-negative matrix factorization: the matrix V is represented by the two smaller matrices W and H, which, when multiplied, approximately **reconstruct V**.*

## **Verband (Lattice) & Algebren**

##### **Verband (Lattice)**

Ein Verband ist ein Tripel (V, ⊓, ⊔), bestehend aus einer nichtleeren Menge V und zwei Operationen ⊓ : V×V →V (lies: et)und ⊔ : V×V →V (lies:vel), fur die folgende Rechenregeln gelten:

* Beide Operationen sind **kommutativ**, d. h., u⊓v = v⊓u und u⊔v = v⊔u f u ̈ r a l l e u , v ∈ V .

* Beide Operationen sind **assoziativ**, d. h., (u ⊓ v) ⊓ w = u ⊓ (v ⊓ w) und ( u ⊔ v ) ⊔ w = u ⊔ ( v ⊔ w ) f u ̈ r a l l e u , v , w ∈ V .

* Es gelten die **Verschmelzungsgesetze**, d. h., u⊓(u⊔v) = u und u⊔(u⊓v) = u f u ̈ r a l l e u , v ∈ V .

Ein Verband (V,⊓,⊔) wird auch kuerzer V geschrieben, sofern klar ist, um welche Operationen es sich handelt. Ein Verband V heißt endlich, wenn die Menge V endlich ist.

* Ein Verband ist eine algebraische Struktur, **deren zwei innere Verknüpfungen im allgemeinen Fall nicht als Addition und Multiplikation aufgefasst werden können** (zB grösser gleich und kleiner gleich Relationen zwischen Mengenelementen)

* Als algebraische Struktur ist ein Verband dadurch gekennzeichnet, dass es zwei assoziative und kommutative Operationen gibt, für die die Absorptionsgesetze kennzeichnend sind: Für beliebige Elemente gilt u ∨ (u ∧ v) = u und u ∧ (u ∨ v) = u.

* Für jede in der Verbandstheorie vorkommende algebraische Aussage gibt es eine direkte Übersetzung in eine Ordnungsaussage und umgekehrt.

Ein Verband $(V, \vee, \wedge)$ ist eine Menge $V$ mit zwei inneren binären Verknüpfungen $\vee$ (Vereinigung, engl. join) und $\wedge$ (Durchschnitt, engl. meet), die folgenden Bedingungen für alle $u, v, w$ aus $V$ genügen:

**Assoziativgesetze**:

$ u \vee(v \vee w)=(u \vee v) \vee w$

$ u \wedge(v \wedge w)=(u \wedge v) \wedge w$

**Kommutativgesetze**:

$ u \vee \boldsymbol{v}=v \vee u$

$ u \wedge v=v \wedge u$

**Absorptionsgesetze**:

$ u \vee(u \wedge v)=u$

$ u \wedge(u \vee v)=u$

Aus diesen Bedingungen folgt die [**Idempotenz**](https://de.m.wikipedia.org/wiki/Idempotenz) beider Verknüpfungen:

$ u \vee \boldsymbol{u}=u$

$ u \wedge u=u$

**$V$ ist also bezüglich jeder einzelnen Verknüpfung ein Halbverband, $d$. h. eine kommutative [Halbgruppe](https://de.m.wikipedia.org/wiki/Halbgruppe),** der jedes Element idempotent ist. Die Verknüpfungen treten bei den Absorptionsgesetzen in
Wechselwirkung.

**Beispiele für Verbände:**

* Die Menge aller Aussagen bildet zusammen mit Konjunktion und Disjunktion nach Satz 1.9 einen Verband, den so genannten Aus- sagenverband.

* Die Potenzmenge P (A) einer Menge A bildet zusammen mit Durchschnitt und Vereinigung nach Satz 3.7 den Potenzmengenverband von A.

* Die Menge aller natuerlichen Zahlen N<sub>0</sub> bildet mit ggT und kgV nach Kap. 13 den so genannten natu ̈rlichen Teilerverband.

* Die Menge aller Unterra ̈ume eines Vektorraums V bildet mit Durchschnitt und Summe den so genannten Unterraumverband von V , wobei die Summe durchU+W ={u+w|u∈U,w∈W}gegebenist.

* die z. B. in der Mengenlehre, der Logik und als Schaltalgebren auftretenden Booleschen Algebren sind Verbände.

* [totale Ordnungen](https://de.m.wikipedia.org/wiki/Ordnungsrelation#Totalordnung), die z. B. in den verschiedenen Zahlbereichen wie N  (natürliche Zahlen), Z (ganze Zahlen), Q (rationale Zahlen) oder R (reelle Zahlen) auftreten, sind Verbände.

* für jede beliebige natürliche Zahl ist die Menge der Teiler (durch die Teilbarkeit geordnet) ein Verband.

* die Unterstrukturen einer beliebigen algebraischen oder sonstigen Struktur bilden einen Verband mit der Teilmengenrelation als Ordnung.

* ALSO: Das Hasse-Diagramm zeigt die Teiler der Zahl 12, bezüglich der durch die Teilbarkeit gegebenen Ordnungsbeziehung (https://mathepedia.de/Hasse_Diagramme.html)

https://de.m.wikipedia.org/wiki/Verband_(Mathematik)

https://en.m.wikipedia.org/wiki/Lattice_(order)

**Ordnungstheorie**: https://mathepedia.de/Verbaende.html

https://en.wikipedia.org/wiki/Algebraic_structure

Check: Two sets with operations

https://de.m.wikipedia.org/wiki/Algebraische_Struktur

**Absorption (Logik)**

* Das Absorptionsgesetz der Aussagenlogik besagt, dass eine Aussage absorbiert wird, d. h., dass ihre Belegung für die Auswertung der Gesamtformel irrelevant ist, wenn sie hintereinander konjunktiv und disjunktiv mit einer anderen Aussage verknüpft wird, wobei die Reihenfolge der Verknüpfungen keine Rolle spielt.

Absorptionsgesetze in der Verbandstheorie:

$u \vee(u \wedge v)=u$

$u \wedge(u \vee v)=u$

https://de.m.wikipedia.org/wiki/Absorption_(Logik)

**Hintergrund zu Verbaenden**

* Das Verbandskonzept geht auf Dedekind und Schroeder zurueck (Ende des 19. Jahrhunderts).

* Bei Dedekind heißen solche Strukturen Dualgruppen. Der Name Verband wurde von Fritz Klein (ca. 1930) gewaehlt. Garrett Birkhoff, der Begruender der modernen Verbandstheorie, praegte den englischen Begriff lattice.

* Ein Verband ist **eine Struktur, die sowohl als [Ordnungsstruktur (Ordnungsrelation)](https://de.m.wikipedia.org/wiki/Ordnungsrelation) als auch als [algebraische Struktur](https://de.m.wikipedia.org/wiki/Algebraische_Struktur)** vollständig beschrieben werden kann. 

* Als Ordnungsstruktur ist ein Verband dadurch gekennzeichnet, dass es zu je zwei Elementen 
a, 
b ein Supremum 
a
∨
b gibt, d. h. ein eindeutig bestimmtes kleinstes Element, das größer oder gleich
a und 
b ist, und umgekehrt ein Infimum 
a
∧
b, ein größtes Element, das kleiner oder gleich 
a und
b ist. 

* Als algebraische Struktur ist ein Verband dadurch gekennzeichnet, dass es zwei assoziative und kommutative Operationen gibt, für die die Absorptionsgesetze kennzeichnend sind: Für beliebige Elemente gilt

> $u \vee(u \wedge v)=u$ und $u \wedge(u \vee v)=u$

* **Für jede in der Verbandstheorie vorkommende algebraische Aussage gibt es eine direkte Übersetzung in eine Ordnungsaussage und umgekehrt**. Diese Übersetzung ist in den meisten Fällen auch anschaulich nachzuvollziehen. 

* Die Möglichkeit, Ergebnisse doppelt zu interpretieren und dadurch besser zu verstehen, macht die Untersuchung und die Verwendung von Aussagen aus der Verbandstheorie so interessant. Der Begriff Verband wurde im hier beschriebenen Sinne von Fritz Klein-Barmen geprägt.

##### **Algebren**

https://mathepedia.de/Algebren.html

Eine Algebra (Plural: Algebren) **ist eine Verallgemeinerung des Begriffes Ring**.
Es gibt zwei grundsätzlich verschiedene Arten von Algebren:

1. Boolesche Algebren, insbesondere Mengenalgebren wie z.B. σ-Algebren

2. Algebren über Ringen, die eine Art Synthese aus den Begriffen Vektorraum und Ring darstellen.

**Boolsche Algebra**

* Eine **Boolesche Algebra (oder ein boolescher Verband) ist ein Verband**, bzw. eine spezielle algebraische Struktur, die die Eigenschaften der logischen Operatoren UND, ODER, NICHT sowie die Eigenschaften der mengentheoretischen Verknüpfungen Durchschnitt, Vereinigung, Komplement verallgemeinert. 

* Gleichwertig zu booleschen Algebren sind boolesche Ringe, die von UND und ENTWEDER-ODER (exklusiv-ODER) beziehungsweise Durchschnitt und symmetrischer Differenz ausgehen.

* Die boolesche Algebra ist die Grundlage bei der Entwicklung von digitaler Elektronik und wird in allen modernen Programmiersprachen zur Verfügung gestellt. Sie wird auch in der Satztheorie und der Statistik verwendet.

* Eine **Boolesche Algebra (oder ein boolescher Verband) ist ein Verband**, in dem die beiden Verknüpfungen je ein neutrales Element haben, a ∪ 0 = a und a ∩ 1 = a, und in dem jedes Element ein bezüglich beider Verknüpfungen übereinstimmendes Komplement h

**Definition der Boolschen Algebra als Verband:**

* **Eine boolesche Algebra ist ein distributiver komplementärer Verband**. Diese Definition geht nur von den Verknüpfungen $\wedge$ und $\vee$ aus und umfasst die Existenz von 0,1 und $\neg$ und die unabhängigen Axiome (1)$\left(1^{\prime}\right)(2)$ $\left(2^{\prime}\right)(11)\left(11^{\prime}\right)(4)(9)\left(9^{\prime}\right)$ des gleichwertigen Axiomensystems von Peano. 

* Auf einer booleschen Algebra ist wie in jedem Verband durch $a \leq b \Longleftrightarrow a=a \wedge b$ eine partielle Ordnung definierbar; bei ihr haben je zwei Elemente ein Supremum und ein Infimum. 

* Bei der mengentheoretischen Interpretation ist $\leq$ gleichbedeutend zur Teilmengenordnung $\subseteq$

**Boolesche Ringe**

* Eine andere Sichtweise auf boolesche Algebren besteht in sogenannten booleschen Ringen: Das sind Ringe mit Einselement, die zusätzlich idempotent sind, also das Idempotenzgesetz 
a
⋅
a
=
a erfüllen. 

* Jeder idempotente Ring ist kommutativ. Die Addition im booleschen Ring entspricht bei der mengentheoretischen Interpretation der symmetrischen Differenz und bei aussagenlogischer Interpretation der Alternative ENTWEDER-ODER (exclusiv-ODER, XOR); die Multiplikation entspricht der Durchschnittsbildung beziehungsweise der Konjunktion UND.

https://de.m.wikipedia.org/wiki/Aussagenlogik

https://de.m.wikipedia.org/wiki/Boolesche_Algebra

**Mengenalgebra (Field of Sets)**

Die Potenzmenge einer Menge $S$ wird mit Durchschnitt, Vereinigung und dem Komplement $A^{\complement}:=\{x \mid(x \in S) \wedge(x \notin A)\}$ zu einer booleschen Algebra, bei der 0 die leere Menge $\emptyset$ und 1 die ganze Menge $S$ ist. Der Sonderfall $S=\emptyset$ ergibt die einelementige Potenzmenge mit $1=0 .$ 

Auch jeder $S$ enthaltende, bezüglich Vereinigung und Komplement abgeschlossene Teilbereich der Potenzmenge von $S$ ist eine boolesche Algebra, die als Teilmengenverband oder Mengenalgebra bezeichnet wird. Der Darstellungssatz von Stone besagt, dass jede boolesche Algebra isomorph (s. u.) zu einer Mengenalgebra ist. Daraus folgt, dass die Mächtigkeit jeder endlichen booleschen
Algebra eine Zweierpotenz ist.

Über die Venn-Diagramme veranschaulicht die Mengenalgebra boolesche Gesetze, beispielsweise Distributiv- und deMorgansche-Gesetze. Darüber hinaus basiert auf ihrer Form als KV-Diagramm eine bekannte Methode der systematischen Vereinfachung boolescher Ausdrücke in der Schaltalgebra.
Weitere Beispiele für boolesche Mengenalgebren stammen aus der Topologie. 

Die Menge der abgeschlossenen offenen Mengen eines topologischen Raums bildet mit den üblichen Operationen für die Vereinigung, den Durchschnitt und das Komplement von Mengen eine boolesche Algebra. Die regulär abgeschlossenen Mengen und die regulär offenen Mengen stellen mit den jeweiligen regularisierten Mengenoperationen $\cap^{*}, \cup^{*}$ und $C^{*}$ ebenfalls boolesche Algebren dar.

* **Mengenalgebra**: eine Boolesche Algebra, deren Elemente Mengen sind, nämlich Teilmengen einer Grundmenge X, mit den Mengenoperatoren ∪ und ∩ als Verknüpfungen, mit dem Nullelement ∅ und dem Einselement X.

* **σ-Algebra**: eine bezüglich abzählbar-unendlicher Verknüpfungen abgeschlossene Mengenalgebra. **Messraum und Maßraum sind spezielle σ-Algebren.**

* **Borel-Algebra** macht einen topologischen Raum zum Maßraum: sie ist die kleinste σ-Algebra, die eine gegebene Topologie enthält.

* **Zweiwertige Boolesche Algebra**: hat nur die Elemente 0 und 1.

https://de.m.wikipedia.org/wiki/Algebra_(Mengensystem)