<a href="https://colab.research.google.com/github/deltorobarba/machinelearning/blob/master/qr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **QR Decomposition**

In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

* The QR decomposition is for m x n matrices (not limited to square matrices) and decomposes a matrix into Q and R components.

> A = Q . R

* Where A is the matrix that we wish to decompose, Q a matrix with the size m x m, and R is an upper triangle matrix with the size m x n.

* The QR decomposition is found using an iterative numerical method that can fail for those matrices that cannot be decomposed, or decomposed easily.

* Like the LU decomposition, the QR decomposition is often used to solve systems of linear equations, although is not limited to square matrices.

* The QR decomposition can be implemented in NumPy using the qr() function. By default, the function returns the Q and R matrices with smaller or ‘reduced’ dimensions that is more economical. We can change this to return the expected sizes of m x m for Q and m x n for R by specifying the mode argument as ‘complete’, although this is not required for most applications.

**Define Matrix**

In [0]:
from numpy import array

# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


**Decompose**

In [0]:
# QR decomposition
from numpy.linalg import qr
Q, R = qr(A, 'complete')

In [0]:
print(Q)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]


In [0]:
print(R)

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


**Reconstruct**

In [0]:
B = Q.dot(R)
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
